apiVersion: v2
name: argo-workflows
type: application
version: 0.1.0
appVersion: v3.4.8
dependencies:
  - name: argo-workflows
    version: 0.29.2
    repository: https://argoproj.github.io/argo-helm
